#ifndef FACEDETECTIONPLUGIN_GLOBAL_H
#define FACEDETECTIONPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef FACEDETECTIONPLUGIN_LIB
# define FACEDETECTIONPLUGIN_EXPORT Q_DECL_EXPORT
#else
# define FACEDETECTIONPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // FACEDETECTIONPLUGIN_GLOBAL_H
